# Generated by Django 5.1.2 on 2024-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('race', models.CharField(max_length=50, verbose_name='Raza')),
                ('attribute', models.CharField(max_length=50, verbose_name='Attribute')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
